# Generated by Django 3.2.3 on 2021-06-24 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_userdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='confirmpassword',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
