# Generated by Django 3.2.3 on 2021-06-25 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_userdetails_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='confirmpassword',
        ),
    ]
